Add context awareness
remeh/sizedwaitgroup pull request #5
Opened 2018-08-15 13:55 UTC by hstern

This allows for the Add call to be interrupted by context cancellation.

2018-08-16 06:53 UTC, remeh commented
Hello Henry, thanks for the pull-request! I'll check this out soon.

2018-08-17 07:29 UTC, remeh requested changes
Hi Henry,

I think it would be better to do it another way: simply by adding a method called `AddWithContext(ctx context.Context)`.

The Go documentation mentions that it is not a good practice to store a context inside a struct (see https://golang.org/pkg/context/), it would also be more idiomatic as many packages of the standard library have chosen this solution. On top of that, it would avoid having to return an `error`/`nil` in the method `Add()`.

2018-08-17 07:29 UTC, remeh commented on sizedwaitgroup.go
> +func (s *SizedWaitGroup) Add() error {
I like your PR, I'm just wondering about this signature change, the fact that it now returns an error. I definitely understand why but I'm wondering if it is a good thing.

2018-08-22 14:37 UTC, hstern commented
@remeh There are lots of modules in the standard go library that store contexts (eg. http.Request) but you're right that it's poor practice. Is 0da8c97 more to your liking?

2018-08-22 14:42 UTC, remeh commented
Hi @hstern , that looks perfect! Thank you for your contribution!

2018-08-22 14:42 UTC, merged